# Generated by Django 4.2.28 on 2026-03-01 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Category name, e.g., 'Residential', 'Commercial'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this category', null=True)),
            ],
            options={
                'verbose_name_plural': 'Floor Plan Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlanDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the floor plan dataset', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the floor plan', null=True)),
                ('image', models.ImageField(help_text='2D Floor plan image file', upload_to='floor_plans/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='builder_dashboard.floorplancategory')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_floor_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
