# Generated by Django 4.2.28 on 2026-03-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0002_floorplancategory_floorplandataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='engagement_tier',
            field=models.CharField(choices=[('DIT', 'Do It Together'), ('DIFY', 'Do It For You')], default='DIT', max_length=10),
        ),
    ]
