# Generated by Django 4.2.28 on 2026-03-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0003_alter_project_engagement_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplandataset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='floorplandataset',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='project',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='project',
        ),
        migrations.DeleteModel(
            name='ChangeOrder',
        ),
        migrations.DeleteModel(
            name='FloorPlanCategory',
        ),
        migrations.DeleteModel(
            name='FloorPlanDataset',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
