# Generated by Django 4.2.28 on 2026-03-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0004_remove_floorplandataset_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor_claim', models.TextField(help_text="Contractor's delay claim description")),
                ('claimed_delay_days', models.PositiveIntegerField()),
                ('actual_rainfall_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('verdict', models.CharField(choices=[('approved', 'Delay Approved'), ('rejected', 'Delay Rejected'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_events', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('recording', models.BooleanField(default=False)),
                ('stream_url', models.URLField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_cameras', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_name', models.CharField(max_length=255)),
                ('delivered_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installed_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('theoretical_usage', models.DecimalField(decimal_places=2, help_text='Expected usage based on installed qty', max_digits=12)),
                ('actual_usage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('audit_passed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_audits', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ESignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('payment_release', 'Payment Release'), ('variation_order', 'Variation Order')], max_length=30)),
                ('party_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esignature_requests', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='EscrowMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('locked', 'Locked')], default='locked', max_length=20)),
                ('released', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_milestones', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue')], default='upcoming', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_schedules', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
