# Generated by Django 4.2.28 on 2026-03-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0005_weatherevent_sitecamera_materialaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Preliminaries', 'Preliminaries'), ('Substructure', 'Substructure'), ('Superstructure', 'Superstructure'), ('Walling', 'Walling'), ('Roofing', 'Roofing'), ('Doors & Windows', 'Doors & Windows'), ('Finishes', 'Finishes'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('External Works', 'External Works'), ('Provisional Sums', 'Provisional Sums'), ('Other', 'Other')], default='Other', max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(help_text='e.g. m², m³, nr, kg, item', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('labour_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('measurement_formula', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='builder_dashboard.project')),
            ],
            options={
                'verbose_name': 'BOQ Item',
                'verbose_name_plural': 'BOQ Items',
                'ordering': ['category', 'created_at'],
            },
        ),
    ]
