# Generated by Django 4.2.28 on 2026-03-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0006_boqitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='category',
            field=models.CharField(choices=[('1. Preliminaries & General', '1. Preliminaries & General'), ('2. Earthworks & Excavation', '2. Earthworks & Excavation'), ('3. Concrete, Formwork & Reinforcement', '3. Concrete, Formwork & Reinforcement'), ('4. Brickwork & Blockwork', '4. Brickwork & Blockwork'), ('5. Waterproofing', '5. Waterproofing'), ('6. Carpentry, Joinery & Ironmongery', '6. Carpentry, Joinery & Ironmongery'), ('7. Roof Coverings', '7. Roof Coverings'), ('8. Plumbing & Drainage', '8. Plumbing & Drainage'), ('9. Electrical Installations', '9. Electrical Installations'), ('10. Floor, Wall & Ceiling Finishes', '10. Floor, Wall & Ceiling Finishes'), ('11. Glazing & Painting', '11. Glazing & Painting'), ('12. External Works', '12. External Works'), ('13. Provisional & Prime Cost Sums', '13. Provisional & Prime Cost Sums')], default='Other', max_length=50),
        ),
    ]
