# Generated by Django 4.2.28 on 2026-03-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0009_project_brief_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_name', models.CharField(max_length=255)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=30)),
                ('procurement_method', models.CharField(choices=[('SELF', 'Procure by Yourself'), ('GROUP_BUY', 'Group Buy Aggregator')], default='SELF', max_length=20)),
                ('price_at_request', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('group_buy_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_calculated_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='builder_dashboard.boqitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
