# Generated by Django 4.2.28 on 2026-03-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0010_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_budget_signed',
            field=models.BooleanField(default=False, help_text='Indicates if the construction budget has been signed by the builder'),
        ),
    ]
