# Generated by Django 4.2.28 on 2026-03-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder_dashboard', '0012_drawingrequest_drawingfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='architect',
            field=models.ForeignKey(blank=True, help_text='Primary architect assigned to this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
