# Generated by Django 4.2.28 on 2026-03-14 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder_dashboard', '0013_project_architect'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('architect', 'Architect'), ('structural_engineer', 'Structural Engineer'), ('contractor', 'General Contractor'), ('project_manager', 'Project Manager'), ('quantity_surveyor', 'Quantity Surveyor'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('mason', 'Mason/Bricklayer'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('roofer', 'Roofer'), ('tiler', 'Tiler')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='builder_dashboard.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'created_at'],
                'unique_together': {('project', 'user', 'role')},
            },
        ),
    ]
