# Generated by Django 4.2.28 on 2026-03-20 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder_dashboard', '0014_projectteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='True if this item was generated by the AI analyser'),
        ),
        migrations.CreateModel(
            name='BOQCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created Manually'), ('UPDATE', 'Modified AI Item'), ('DELETE', 'Deleted AI Item')], max_length=10)),
                ('was_ai_generated', models.BooleanField(default=False)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='builder_dashboard.boqitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_corrections', to='builder_dashboard.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
