# Generated by Django 4.2.28 on 2026-03-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('builder_dashboard', '0015_boqitem_is_ai_generated_boqcorrection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boqcorrection',
            name='boq_item',
        ),
        migrations.AddField(
            model_name='boqcorrection',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='boqcorrection',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BOQScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wbs', models.CharField(blank=True, max_length=50, null=True)),
                ('task_description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.CharField(blank=True, max_length=50, null=True)),
                ('predecessor', models.CharField(blank=True, max_length=100, null=True)),
                ('est_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tasks', to='builder_dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOQProfessionalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.CharField(blank=True, max_length=255, null=True)),
                ('role_scope', models.TextField(blank=True, null=True)),
                ('basis', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_fees', to='builder_dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOQMachinePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_item', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('dry_hire_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_l_hr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hrs_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('operator_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_wet_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_rqd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_plants', to='builder_dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOQLabourCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_role', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_level', models.CharField(blank=True, max_length=100, null=True)),
                ('gang_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_weeks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_man_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('weekly_wage_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_costs', to='builder_dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOQLabourBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_role', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_level', models.CharField(blank=True, max_length=100, null=True)),
                ('gang_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_weeks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_man_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_breakdowns', to='builder_dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOQBuildingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if generated by AI')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_items', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOQAdminExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_role', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trips_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_trips', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_expenses', to='builder_dashboard.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='boq_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='builder_dashboard.boqbuildingitem'),
        ),
        migrations.DeleteModel(
            name='BOQItem',
        ),
    ]
