# Generated by Django 4.2.28 on 2026-03-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('builder_dashboard', '0016_remove_boqcorrection_boq_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='procurement_category',
            field=models.CharField(choices=[('MATERIAL', 'Building Material'), ('LABOUR', 'Labour'), ('PLANT', 'Plant & Equipment'), ('PROFESSIONAL', 'Professional Fee'), ('ADMIN', 'Admin & Expense'), ('OTHER', 'Other')], default='MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
