# Generated by Django 4.2.28 on 2026-03-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0017_materialrequest_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqbuildingitem',
            name='specification',
            field=models.TextField(blank=True, help_text='Material specification details', null=True),
        ),
        migrations.CreateModel(
            name='ScheduleOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('SUBSTRUCTURE', 'Substructure'), ('SUPERSTRUCTURE', 'Superstructure'), ('ROOFING_CEILINGS', 'Roofing & Ceilings'), ('FINISHES', 'Finishes'), ('DOORS_WINDOWS', 'Doors & Windows'), ('PLUMBING', 'Plumbing & Drainage'), ('ELECTRICAL_SOLAR', 'Electrical & Solar Off-Grid')], max_length=50)),
                ('material_description', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True, help_text='Detailed material specification', null=True)),
                ('estimated_qty', models.CharField(blank=True, help_text="Estimated quantity with units, e.g. '50,000 units'", max_length=100, null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_materials', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['section', 'created_at'],
            },
        ),
    ]
