# Generated by Django 4.2.28 on 2026-02-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'HelpCircle')", max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Help Center Category',
                'verbose_name_plural': 'Help Center Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('TERMS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Full content of the document')),
                ('is_active', models.BooleanField(default=True, help_text='Only active documents are shown to users')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='HelpCenterArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('content', models.TextField(help_text='Full content of the article')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for preview', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0, help_text='Number of times viewed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.helpcentercategory')),
            ],
            options={
                'verbose_name': 'Help Center Article',
                'verbose_name_plural': 'Help Center Articles',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(help_text='Full answer to the question')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0, help_text='Number of times viewed')),
                ('category', models.ForeignKey(blank=True, help_text='Optional category for grouping FAQs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.helpcentercategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', 'question'],
            },
        ),
    ]
