# Generated by Django 4.2.28 on 2026-03-22 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Category name, e.g., 'Residential', 'Commercial'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this category', null=True)),
            ],
            options={
                'verbose_name_plural': 'Floor Plan Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='AfriConTech Hub', max_length=255)),
                ('tagline', models.CharField(blank=True, default="Building Africa's Future", max_length=500)),
                ('support_email', models.EmailField(blank=True, default='support@africacontechhub.com', max_length=254)),
                ('registration_open', models.BooleanField(default=True, help_text='Allow new user registrations')),
                ('require_approval', models.BooleanField(default=True, help_text='Require admin approval for new accounts')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Put platform in maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, default='We are currently performing maintenance. Please check back soon.')),
                ('default_role', models.CharField(choices=[('BUILDER', 'Builder'), ('CONTRACTOR', 'Contractor'), ('SUPPLIER', 'Supplier')], default='BUILDER', max_length=20)),
                ('max_projects_per_user', models.PositiveIntegerField(default=10)),
                ('max_file_upload_mb', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='FloorPlanDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the floor plan dataset', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the floor plan', null=True)),
                ('image', models.ImageField(help_text='2D Floor plan image file', upload_to='floor_plans/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='admin_dashboard.floorplancategory')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_floor_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_DELETED', 'User Deleted'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_TOGGLED', 'User Activated/Deactivated'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('SETTINGS_CHANGED', 'Settings Changed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('OTHER', 'Other')], max_length=30)),
                ('target_type', models.CharField(blank=True, help_text='e.g. User, AccountRequest, Document', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, help_text='Human-readable target description', max_length=255)),
                ('detail', models.TextField(blank=True, help_text='Extra context about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
