# Generated by Cursor on 2026-04-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('CLICK', 'Click'), ('ACTION', 'Action'), ('OTHER', 'Other')], default='PAGE_VIEW', max_length=20)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('referrer', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Event',
                'verbose_name_plural': 'User Activity Events',
                'ordering': ['-created_at'],
            },
        ),
    ]

