# Generated by Django 4.2.27 on 2025-12-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('TERMS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Full content of the document')),
                ('is_active', models.BooleanField(default=True, help_text='Only active documents are shown to users')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['document_type'],
            },
        ),
    ]
