# Generated by Django 4.2.27 on 2025-12-22 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'HelpCircle')", max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Help Center Category',
                'verbose_name_plural': 'Help Center Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpCenterArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('content', models.TextField(help_text='Full content of the article')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for preview', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0, help_text='Number of times viewed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.helpcentercategory')),
            ],
            options={
                'verbose_name': 'Help Center Article',
                'verbose_name_plural': 'Help Center Articles',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
