# Generated by Django 4.2.27 on 2025-12-22 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_helpcentercategory_helpcenterarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(help_text='Full answer to the question')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0, help_text='Number of times viewed')),
                ('category', models.ForeignKey(blank=True, help_text='Optional category for grouping FAQs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.helpcentercategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', 'question'],
            },
        ),
    ]
