# Generated by Django 4.2.28 on 2026-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_architecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction_text', models.TextField(default='You are the DzeNhare Architecture AI, a helpful, professional AI assistant built into the builder dashboard. You specialize in construction, compliance regulations (like SI-56), and architectural guidance. Keep answers concise, helpful, and professional.', help_text='The system prompt instructing the AI how to behave and what its role is.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Instruction Configuration',
                'verbose_name_plural': 'AI Instruction Configurations',
            },
        ),
    ]
