# Generated by Django 4.2.28 on 2026-02-28 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_architecture', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingStylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Floor Plan'", max_length=100)),
                ('category', models.CharField(choices=[('FLOOR_PLAN', 'Floor Plan'), ('ELEVATION', 'Elevation'), ('SITE_PLAN', 'Site Plan'), ('SECTION', 'Section View'), ('3D_RENDER', '3D Render'), ('LANDSCAPE', 'Landscape Design'), ('DETAIL', 'Construction Detail'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('keywords', models.TextField(help_text="Comma-separated trigger keywords, e.g. 'floor plan, floorplan, room layout'")),
                ('prompt_template', models.TextField(default='Create a highly detailed architectural {category} based on this request: {user_request}. Use clean black-and-white line work, professional drafting style, labeled rooms with dimensions, and a top-down orthographic view. Include a title block and north arrow.', help_text="Template injected into Qwen's prompt-engineering step. Use {user_request} as placeholder for the original user message.")),
                ('negative_prompt', models.TextField(blank=True, default='blurry, low quality, realistic photo, 3d render, watermark, text overlay, cartoonish', help_text='What to avoid in the generated image.')),
                ('style_tokens', models.TextField(blank=True, default='architectural blueprint, technical drawing, clean lines, professional CAD', help_text='Extra style keywords appended to every prompt of this type.')),
                ('guidance_scale', models.FloatField(default=7.5, help_text='FLUX guidance scale (higher = more prompt adherence, 3-15 typical).')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority presets are matched first when keywords overlap.')),
            ],
            options={
                'verbose_name': 'Drawing Style Preset',
                'verbose_name_plural': 'Drawing Style Presets',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('original_prompt', models.TextField(help_text='The exact prompt that was sent to FLUX for this image.')),
                ('feedback_text', models.TextField(blank=True, help_text='Optional user comment.')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_architecture.chatmessage')),
                ('preset_used', models.ForeignKey(blank=True, help_text='Which style preset was active when this image was generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_architecture.drawingstylepreset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Feedback',
                'verbose_name_plural': 'Image Feedback',
                'ordering': ['-created_at'],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
