# Generated by Django 4.2.28 on 2026-03-01 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_architecture', '0004_drawingstylepreset_imagefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(default='Untitled Project', max_length=255)),
                ('item_name', models.CharField(help_text="e.g. 'Strip Footing Excavation'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Any additional context provided by the AI')),
                ('unit', models.CharField(help_text="e.g. 'm', 'm2', 'm3', 'Lm', 'No.'", max_length=50)),
                ('quantity', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOQ Measurement',
                'verbose_name_plural': 'BOQ Measurements',
                'ordering': ['-created_at'],
            },
        ),
    ]
