# Generated by Django 4.2.28 on 2026-03-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_architecture', '0005_boqmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqmeasurement',
            name='category',
            field=models.CharField(default='Uncategorized', help_text='e.g. Substructure, Roofing, Finishes', max_length=100),
        ),
        migrations.AddField(
            model_name='boqmeasurement',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit rate or cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='boqmeasurement',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity * Rate', max_digits=15),
        ),
    ]
