# Generated by Django 4.2.28 on 2026-03-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_architecture', '0006_boqmeasurement_category_boqmeasurement_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BOQMeasurement',
        ),
    ]
