# Generated by Django 4.2.28 on 2026-03-02 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_architecture', '0007_delete_boqmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash of file content for deduplication', max_length=64),
        ),
        migrations.AlterField(
            model_name='drawingstylepreset',
            name='guidance_scale',
            field=models.FloatField(default=7.5, help_text='Gemini guidance scale (higher = more prompt adherence, 3-15 typical).'),
        ),
        migrations.AlterField(
            model_name='drawingstylepreset',
            name='prompt_template',
            field=models.TextField(default='Create a highly detailed architectural {category} based on this request: {user_request}. Use clean black-and-white line work, professional drafting style, labeled rooms with dimensions, and a top-down orthographic view. Include a title block and north arrow.', help_text="Template injected into Claude's prompt-engineering step. Use {user_request} as placeholder for the original user message."),
        ),
        migrations.AlterField(
            model_name='imagefeedback',
            name='original_prompt',
            field=models.TextField(help_text='The exact prompt that was sent to Gemini for this image.'),
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(db_index=True, help_text='e.g. cement, river sand, roofing sheets', max_length=120)),
                ('unit', models.CharField(help_text='e.g. 50kg bag, m³, sheet', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWL', 'Zimbabwe Dollar'), ('ZAR', 'South African Rand')], default='USD', max_length=3)),
                ('region', models.CharField(db_index=True, default='Zimbabwe', max_length=100)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Material Price',
                'verbose_name_plural': 'Material Prices',
                'ordering': ['material', 'region'],
                'unique_together': {('material', 'region', 'supplier_name')},
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(choices=[('chat', 'Chat Completion'), ('stream', 'Chat Stream'), ('analyse', 'BOQ Analyse'), ('draw', 'Image Generation'), ('tools', 'Tool Use')], default='chat', max_length=20)),
                ('model_name', models.CharField(default='', max_length=80)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_architecture.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_architec_user_id_d0d957_idx'), models.Index(fields=['endpoint', '-created_at'], name='ai_architec_endpoin_e32663_idx')],
            },
        ),
    ]
