# Generated by Django 4.2.28 on 2026-03-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_architecture', '0008_knowledgedocument_content_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default BOQ Format', help_text='Display name for this template.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('category_order', models.TextField(default='1. Preliminaries\n2. Substructure\n3. Superstructure — Walling\n4. Superstructure — Roofing\n5. Finishes — Internal\n6. Finishes — External\n7. Windows & Doors\n8. Plumbing & Drainage\n9. Electrical\n10. External Works\n11. Provisional Sums & Contingencies', help_text='Numbered list of BOQ categories in the order they must appear. The AI will group extracted items under these headings.')),
                ('extraction_rules', models.TextField(default="• Always include Preliminaries (site establishment, water, temporary works).\n• For walls: distinguish between external load-bearing (230 mm) and internal partition (115 mm). Measure in m² per wall type.\n• For concrete: separate strip foundations, floor slabs, and lintels. Measure in m³.\n• For roofing: include roof covering (sheets / tiles), trusses/rafters, fascia boards, ceiling. Measure covering in m², timber in m.\n• For finishes: separate plaster, paint, screeds, tiling per room. Measure in m².\n• For doors/windows: count per type (e.g. 813×2032 flush door, 1200×1200 aluminium sliding). Measure in nr.\n• For plumbing: list fixtures (WC, basin, shower) and pipework (110 mm soil, 50 mm waste). Measure fixtures in nr, pipes in m.\n• For electrical: list DB boards, circuits, light points, sockets. Measure in nr.\n• If a quantity can't be read from the plan, estimate it and append '(est.)' to the description.\n• Apply standard Zimbabwean rates (USD) unless a rate schedule is attached.", help_text='Rules the AI must follow when extracting items from floor plans. Be specific about what to measure, how to categorize, and units.')),
                ('example_items_json', models.TextField(default='[\n  {"category": "Substructure", "item_name": "Strip Foundation Concrete (C25)", "description": "600×200 mm strip foundation trench concrete", "unit": "m³", "quantity": 8.5, "rate": 120.00, "total_amount": 1020.00},\n  {"category": "Superstructure — Walling", "item_name": "Face Brick External Walls (230 mm)", "description": "Double-skin face brick to external walls as per plan", "unit": "m²", "quantity": 145.0, "rate": 65.00, "total_amount": 9425.00},\n  {"category": "Superstructure — Roofing", "item_name": "IBR Roofing Sheets (0.47 mm)", "description": "Chromadek IBR profile roof covering on timber trusses", "unit": "m²", "quantity": 120.0, "rate": 18.50, "total_amount": 2220.00},\n  {"category": "Windows & Doors", "item_name": "Aluminium Sliding Window 1500×1200", "description": "Powder-coated aluminium sliding window, 6.38 mm laminated glass, supply & fit", "unit": "nr", "quantity": 6, "rate": 280.00, "total_amount": 1680.00}\n]', help_text='JSON array of example BOQ items. These are injected as few-shot examples so the AI learns your preferred naming, description style, and level of detail. Add/edit as many as you need.')),
                ('include_labour_rate', models.BooleanField(default=False, help_text='If True, the AI will separate material rate and labour rate per item.')),
                ('include_measurement_formula', models.BooleanField(default=False, help_text='If True, the AI will show how it calculated each quantity (e.g. 2 × 4.5 × 2.7 = 24.3).')),
                ('header_text', models.TextField(blank=True, default='', help_text='Optional text printed at the top of BOQ exports (e.g. company name, project title).')),
                ('footer_text', models.TextField(blank=True, default='', help_text='Optional text printed at the bottom (e.g. validity note, T&Cs).')),
            ],
            options={
                'verbose_name': 'BOQ Template',
                'verbose_name_plural': 'BOQ Templates',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
