# Generated by Django 4.2.28 on 2026-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_architecture', '0009_boqtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqtemplate',
            name='extraction_rules',
            field=models.TextField(default="• Examine the drawing meticulously — identify ALL distinct elements that require quantification.\n• For each element, extract or calculate dimensions (length × width × height/depth as applicable).\n• Always include Preliminaries (site establishment, water supply, temporary works, setting out).\n• For walls: distinguish external load-bearing (230 mm) vs internal partition (115 mm). Calculate wall area = perimeter × height minus openings. Measure in m².\n• For concrete: separate strip foundations, floor slabs, columns, lintels, ring beams. Calculate volume = L × W × D. Measure in m³.\n• For roofing: include roof covering (sheets/tiles), trusses/rafters, fascia boards, gutters, ceiling. Measure covering in m², timber in m.\n• For finishes: separate plaster, paint, screeds, tiling per room and per surface (walls vs floor vs ceiling). Measure in m².\n• For doors/windows: count per type with exact sizes (e.g. 813×2032 flush door, 1500×1200 aluminium sliding). Include frames, ironmongery. Measure in nr.\n• For plumbing: list fixtures (WC, WHB, shower, sink) and pipework (110 mm soil, 50 mm waste, 15 mm water). Measure fixtures in nr, pipes in m.\n• For electrical: list DB boards, circuits, light points, sockets, switches, earth leakage. Measure in nr.\n• Show the measurement formula for each item (e.g. '2×(12.5+8.0)×2.7 = 110.7 m²').\n• If a quantity can't be read from the plan, estimate it and append '(est.)' to the description.\n• Apply standard Zimbabwean rates (USD) unless a rate schedule is attached.\n• Present items in a logical construction sequence from ground up.", help_text='Rules the AI must follow when extracting items from floor plans. Be specific about what to measure, how to categorize, and units.'),
        ),
        migrations.AlterField(
            model_name='boqtemplate',
            name='include_measurement_formula',
            field=models.BooleanField(default=True, help_text='If True, the AI will show how it calculated each quantity (e.g. 2 × 4.5 × 2.7 = 24.3).'),
        ),
    ]
