# Generated by Django 4.2.28 on 2026-03-13
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0009_project_brief_fields'),
        ('ai_architecture', '0010_alter_boqtemplate_extraction_rules_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteIntel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('rows', models.JSONField(default=list, help_text='Array of {aspect, finding, risk, recommendation}')),
                ('raw_response', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='ai', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_intel_records', to='builder_dashboard.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_intel_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Intelligence',
                'verbose_name_plural': 'Site Intelligence Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
