# Generated by Django 4.2.28 on 2026-03-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_architecture', '0011_siteintel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagefeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imagefeedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='imagefeedback',
            name='preset_used',
        ),
        migrations.RemoveField(
            model_name='imagefeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='DrawingStylePreset',
        ),
        migrations.DeleteModel(
            name='ImageFeedback',
        ),
    ]
