# Generated by Django 4.2.28 on 2026-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True),
        ),
    ]
