# Generated by Django 4.2.27 on 2025-12-22 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder_dashboard', '0005_payment'),
        ('contractor_dashboard', '0002_bid_updated_at_contractorprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True, help_text='Optional comment about the contractor', null=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contractor_dashboard.contractorprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_ratings', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contractor', 'project', 'builder')},
            },
        ),
    ]
