# Generated by Django 5.2.8 on 2025-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteupdate',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='milestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
