# Generated by Django 5.2.8 on 2025-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0002_rename_date_siteupdate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Project latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Project longitude', max_digits=9, null=True),
        ),
    ]
