# Generated by Django 5.2.8 on 2025-11-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_dashboard', '0003_project_latitude_project_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='engagement_tier',
            field=models.CharField(choices=[('DIY', 'Do It Yourself'), ('DIT', 'Do It Together'), ('DIFY', 'Do It For You')], default='DIY', max_length=10),
        ),
    ]
