# Generated by Django 5.2.8 on 2025-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wipaa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
