# Generated by Django 4.2.28 on 2026-03-31 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder_dashboard', '0021_alter_projectbudgetversion_author_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitecturalStudioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='architectural_studio/%Y/%m/')),
                ('category', models.CharField(choices=[('blueprint', 'Technical Blueprint'), ('3d_render', '3D Render'), ('perspective', 'Perspective View'), ('elevation', 'Elevation'), ('section', 'Section'), ('other', 'Other')], default='blueprint', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectural_studio_items', to='builder_dashboard.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
