# Generated by Django 4.2.28 on 2026-03-14 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractor_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorrating',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contractor_dashboard.contractorprofile'),
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('architect', 'Architect'), ('structural_engineer', 'Structural Engineer'), ('contractor', 'General Contractor'), ('project_manager', 'Project Manager'), ('quantity_surveyor', 'Quantity Surveyor'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('mason', 'Mason/Bricklayer'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('roofer', 'Roofer'), ('tiler', 'Tiler')], max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, default='')),
                ('hourly_rate', models.CharField(blank=True, help_text='e.g. $150/hour or Contract basis', max_length=100, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('specialties', models.JSONField(default=list, help_text='List of strings')),
                ('certifications', models.JSONField(default=list, help_text='List of strings')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('completed_projects_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contractorrating',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contractor_dashboard.professionalprofile'),
        ),
    ]
