# Generated by Django 4.2.28 on 2026-03-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_dashboard', '0002_alter_contractorrating_contractor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
