/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSupplierRouteImport } from './routes/_authenticated/supplier'
import { Route as AuthenticatedSqbTeamRouteImport } from './routes/_authenticated/sqb-team'
import { Route as AuthenticatedContractorRouteImport } from './routes/_authenticated/contractor'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authPendingApprovalRouteImport } from './routes/(auth)/pending-approval'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAuthCallbackRouteImport } from './routes/(auth)/auth-callback'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedBuilderIndexRouteImport } from './routes/_authenticated/builder/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedBuilderTaskBoardRouteImport } from './routes/_authenticated/builder/task-board'
import { Route as AuthenticatedBuilderProjectbudgetRouteImport } from './routes/_authenticated/builder/projectbudget'
import { Route as AuthenticatedBuilderProcurementRouteImport } from './routes/_authenticated/builder/procurement'
import { Route as AuthenticatedBuilderGroupBuyRouteImport } from './routes/_authenticated/builder/group-buy'
import { Route as AuthenticatedBuilderFloorPlansRouteImport } from './routes/_authenticated/builder/floor-plans'
import { Route as AuthenticatedBuilderDesignDraftingRouteImport } from './routes/_authenticated/builder/design-drafting'
import { Route as AuthenticatedBuilderContractAnalyserRouteImport } from './routes/_authenticated/builder/contract-analyser'
import { Route as AuthenticatedBuilderBuildingRouteImport } from './routes/_authenticated/builder/building'
import { Route as AuthenticatedBuilderBudgetEngineerRouteImport } from './routes/_authenticated/builder/budget-engineer'
import { Route as AuthenticatedBuilderArchitecturalStudioRouteImport } from './routes/_authenticated/builder/architectural-studio'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin/projects'
import { Route as AuthenticatedAdminProcurementRouteImport } from './routes/_authenticated/admin/procurement'
import { Route as AuthenticatedAdminFloorPlansRouteImport } from './routes/_authenticated/admin/floor-plans'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminDashboardAnalyticsRouteImport } from './routes/_authenticated/admin/dashboard-analytics'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminActivityLogRouteImport } from './routes/_authenticated/admin/activity-log'
import { Route as AuthenticatedBuilderProjectProjectIdRouteImport } from './routes/_authenticated/builder/project.$projectId'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users.$userId'
import { Route as AuthenticatedAdminProjectsProjectIdRouteImport } from './routes/_authenticated/admin/projects.$projectId'
import { Route as AuthenticatedBuilderProjectProjectIdSignaturesRouteImport } from './routes/_authenticated/builder/project.$projectId.signatures'
import { Route as AuthenticatedBuilderProjectProjectIdMaterialsRouteImport } from './routes/_authenticated/builder/project.$projectId.materials'
import { Route as AuthenticatedBuilderProjectProjectIdMaterialRequestsRouteImport } from './routes/_authenticated/builder/project.$projectId.material-requests'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplierRoute = AuthenticatedSupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSqbTeamRoute = AuthenticatedSqbTeamRouteImport.update({
  id: '/sqb-team',
  path: '/sqb-team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractorRoute = AuthenticatedContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authPendingApprovalRoute = authPendingApprovalRouteImport.update({
  id: '/(auth)/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthCallbackRoute = authAuthCallbackRouteImport.update({
  id: '/(auth)/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuilderIndexRoute =
  AuthenticatedBuilderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuilderTaskBoardRoute =
  AuthenticatedBuilderTaskBoardRouteImport.update({
    id: '/task-board',
    path: '/task-board',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderProjectbudgetRoute =
  AuthenticatedBuilderProjectbudgetRouteImport.update({
    id: '/projectbudget',
    path: '/projectbudget',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderProcurementRoute =
  AuthenticatedBuilderProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderGroupBuyRoute =
  AuthenticatedBuilderGroupBuyRouteImport.update({
    id: '/group-buy',
    path: '/group-buy',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderFloorPlansRoute =
  AuthenticatedBuilderFloorPlansRouteImport.update({
    id: '/floor-plans',
    path: '/floor-plans',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderDesignDraftingRoute =
  AuthenticatedBuilderDesignDraftingRouteImport.update({
    id: '/design-drafting',
    path: '/design-drafting',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderContractAnalyserRoute =
  AuthenticatedBuilderContractAnalyserRouteImport.update({
    id: '/contract-analyser',
    path: '/contract-analyser',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderBuildingRoute =
  AuthenticatedBuilderBuildingRouteImport.update({
    id: '/building',
    path: '/building',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderBudgetEngineerRoute =
  AuthenticatedBuilderBudgetEngineerRouteImport.update({
    id: '/budget-engineer',
    path: '/budget-engineer',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedBuilderArchitecturalStudioRoute =
  AuthenticatedBuilderArchitecturalStudioRouteImport.update({
    id: '/architectural-studio',
    path: '/architectural-studio',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProcurementRoute =
  AuthenticatedAdminProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFloorPlansRoute =
  AuthenticatedAdminFloorPlansRouteImport.update({
    id: '/floor-plans',
    path: '/floor-plans',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardAnalyticsRoute =
  AuthenticatedAdminDashboardAnalyticsRouteImport.update({
    id: '/dashboard-analytics',
    path: '/dashboard-analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityLogRoute =
  AuthenticatedAdminActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBuilderProjectProjectIdRoute =
  AuthenticatedBuilderProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminProjectsProjectIdRoute =
  AuthenticatedAdminProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedAdminProjectsRoute,
  } as any)
const AuthenticatedBuilderProjectProjectIdSignaturesRoute =
  AuthenticatedBuilderProjectProjectIdSignaturesRouteImport.update({
    id: '/signatures',
    path: '/signatures',
    getParentRoute: () => AuthenticatedBuilderProjectProjectIdRoute,
  } as any)
const AuthenticatedBuilderProjectProjectIdMaterialsRoute =
  AuthenticatedBuilderProjectProjectIdMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedBuilderProjectProjectIdRoute,
  } as any)
const AuthenticatedBuilderProjectProjectIdMaterialRequestsRoute =
  AuthenticatedBuilderProjectProjectIdMaterialRequestsRouteImport.update({
    id: '/material-requests',
    path: '/material-requests',
    getParentRoute: () => AuthenticatedBuilderProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/auth-callback': typeof authAuthCallbackRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/pending-approval': typeof authPendingApprovalRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/contractor': typeof AuthenticatedContractorRoute
  '/sqb-team': typeof AuthenticatedSqbTeamRoute
  '/supplier': typeof AuthenticatedSupplierRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/dashboard-analytics': typeof AuthenticatedAdminDashboardAnalyticsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/floor-plans': typeof AuthenticatedAdminFloorPlansRoute
  '/admin/procurement': typeof AuthenticatedAdminProcurementRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/builder/architectural-studio': typeof AuthenticatedBuilderArchitecturalStudioRoute
  '/builder/budget-engineer': typeof AuthenticatedBuilderBudgetEngineerRoute
  '/builder/building': typeof AuthenticatedBuilderBuildingRoute
  '/builder/contract-analyser': typeof AuthenticatedBuilderContractAnalyserRoute
  '/builder/design-drafting': typeof AuthenticatedBuilderDesignDraftingRoute
  '/builder/floor-plans': typeof AuthenticatedBuilderFloorPlansRoute
  '/builder/group-buy': typeof AuthenticatedBuilderGroupBuyRoute
  '/builder/procurement': typeof AuthenticatedBuilderProcurementRoute
  '/builder/projectbudget': typeof AuthenticatedBuilderProjectbudgetRoute
  '/builder/task-board': typeof AuthenticatedBuilderTaskBoardRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/builder/': typeof AuthenticatedBuilderIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/builder/project/$projectId': typeof AuthenticatedBuilderProjectProjectIdRouteWithChildren
  '/builder/project/$projectId/material-requests': typeof AuthenticatedBuilderProjectProjectIdMaterialRequestsRoute
  '/builder/project/$projectId/materials': typeof AuthenticatedBuilderProjectProjectIdMaterialsRoute
  '/builder/project/$projectId/signatures': typeof AuthenticatedBuilderProjectProjectIdSignaturesRoute
}
export interface FileRoutesByTo {
  '/auth-callback': typeof authAuthCallbackRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/pending-approval': typeof authPendingApprovalRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/billing': typeof AuthenticatedBillingRoute
  '/contractor': typeof AuthenticatedContractorRoute
  '/sqb-team': typeof AuthenticatedSqbTeamRoute
  '/supplier': typeof AuthenticatedSupplierRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/dashboard-analytics': typeof AuthenticatedAdminDashboardAnalyticsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/floor-plans': typeof AuthenticatedAdminFloorPlansRoute
  '/admin/procurement': typeof AuthenticatedAdminProcurementRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/builder/architectural-studio': typeof AuthenticatedBuilderArchitecturalStudioRoute
  '/builder/budget-engineer': typeof AuthenticatedBuilderBudgetEngineerRoute
  '/builder/building': typeof AuthenticatedBuilderBuildingRoute
  '/builder/contract-analyser': typeof AuthenticatedBuilderContractAnalyserRoute
  '/builder/design-drafting': typeof AuthenticatedBuilderDesignDraftingRoute
  '/builder/floor-plans': typeof AuthenticatedBuilderFloorPlansRoute
  '/builder/group-buy': typeof AuthenticatedBuilderGroupBuyRoute
  '/builder/procurement': typeof AuthenticatedBuilderProcurementRoute
  '/builder/projectbudget': typeof AuthenticatedBuilderProjectbudgetRoute
  '/builder/task-board': typeof AuthenticatedBuilderTaskBoardRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/builder': typeof AuthenticatedBuilderIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/builder/project/$projectId': typeof AuthenticatedBuilderProjectProjectIdRouteWithChildren
  '/builder/project/$projectId/material-requests': typeof AuthenticatedBuilderProjectProjectIdMaterialRequestsRoute
  '/builder/project/$projectId/materials': typeof AuthenticatedBuilderProjectProjectIdMaterialsRoute
  '/builder/project/$projectId/signatures': typeof AuthenticatedBuilderProjectProjectIdSignaturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/auth-callback': typeof authAuthCallbackRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/pending-approval': typeof authPendingApprovalRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/_authenticated/contractor': typeof AuthenticatedContractorRoute
  '/_authenticated/sqb-team': typeof AuthenticatedSqbTeamRoute
  '/_authenticated/supplier': typeof AuthenticatedSupplierRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/dashboard-analytics': typeof AuthenticatedAdminDashboardAnalyticsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/floor-plans': typeof AuthenticatedAdminFloorPlansRoute
  '/_authenticated/admin/procurement': typeof AuthenticatedAdminProcurementRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/builder/architectural-studio': typeof AuthenticatedBuilderArchitecturalStudioRoute
  '/_authenticated/builder/budget-engineer': typeof AuthenticatedBuilderBudgetEngineerRoute
  '/_authenticated/builder/building': typeof AuthenticatedBuilderBuildingRoute
  '/_authenticated/builder/contract-analyser': typeof AuthenticatedBuilderContractAnalyserRoute
  '/_authenticated/builder/design-drafting': typeof AuthenticatedBuilderDesignDraftingRoute
  '/_authenticated/builder/floor-plans': typeof AuthenticatedBuilderFloorPlansRoute
  '/_authenticated/builder/group-buy': typeof AuthenticatedBuilderGroupBuyRoute
  '/_authenticated/builder/procurement': typeof AuthenticatedBuilderProcurementRoute
  '/_authenticated/builder/projectbudget': typeof AuthenticatedBuilderProjectbudgetRoute
  '/_authenticated/builder/task-board': typeof AuthenticatedBuilderTaskBoardRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/builder/': typeof AuthenticatedBuilderIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/builder/project/$projectId': typeof AuthenticatedBuilderProjectProjectIdRouteWithChildren
  '/_authenticated/builder/project/$projectId/material-requests': typeof AuthenticatedBuilderProjectProjectIdMaterialRequestsRoute
  '/_authenticated/builder/project/$projectId/materials': typeof AuthenticatedBuilderProjectProjectIdMaterialsRoute
  '/_authenticated/builder/project/$projectId/signatures': typeof AuthenticatedBuilderProjectProjectIdSignaturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/auth-callback'
    | '/forgot-password'
    | '/otp'
    | '/pending-approval'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin'
    | '/billing'
    | '/builder'
    | '/contractor'
    | '/sqb-team'
    | '/supplier'
    | '/'
    | '/admin/activity-log'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/dashboard-analytics'
    | '/admin/finance'
    | '/admin/floor-plans'
    | '/admin/procurement'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/builder/architectural-studio'
    | '/builder/budget-engineer'
    | '/builder/building'
    | '/builder/contract-analyser'
    | '/builder/design-drafting'
    | '/builder/floor-plans'
    | '/builder/group-buy'
    | '/builder/procurement'
    | '/builder/projectbudget'
    | '/builder/task-board'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/notifications'
    | '/admin/'
    | '/builder/'
    | '/help-center'
    | '/settings/'
    | '/admin/projects/$projectId'
    | '/admin/users/$userId'
    | '/builder/project/$projectId'
    | '/builder/project/$projectId/material-requests'
    | '/builder/project/$projectId/materials'
    | '/builder/project/$projectId/signatures'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-callback'
    | '/forgot-password'
    | '/otp'
    | '/pending-approval'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/billing'
    | '/contractor'
    | '/sqb-team'
    | '/supplier'
    | '/'
    | '/admin/activity-log'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/dashboard-analytics'
    | '/admin/finance'
    | '/admin/floor-plans'
    | '/admin/procurement'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/builder/architectural-studio'
    | '/builder/budget-engineer'
    | '/builder/building'
    | '/builder/contract-analyser'
    | '/builder/design-drafting'
    | '/builder/floor-plans'
    | '/builder/group-buy'
    | '/builder/procurement'
    | '/builder/projectbudget'
    | '/builder/task-board'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/notifications'
    | '/admin'
    | '/builder'
    | '/help-center'
    | '/settings'
    | '/admin/projects/$projectId'
    | '/admin/users/$userId'
    | '/builder/project/$projectId'
    | '/builder/project/$projectId/material-requests'
    | '/builder/project/$projectId/materials'
    | '/builder/project/$projectId/signatures'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/auth-callback'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/pending-approval'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/builder'
    | '/_authenticated/contractor'
    | '/_authenticated/sqb-team'
    | '/_authenticated/supplier'
    | '/_authenticated/'
    | '/_authenticated/admin/activity-log'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/dashboard-analytics'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/floor-plans'
    | '/_authenticated/admin/procurement'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/users'
    | '/_authenticated/builder/architectural-studio'
    | '/_authenticated/builder/budget-engineer'
    | '/_authenticated/builder/building'
    | '/_authenticated/builder/contract-analyser'
    | '/_authenticated/builder/design-drafting'
    | '/_authenticated/builder/floor-plans'
    | '/_authenticated/builder/group-buy'
    | '/_authenticated/builder/procurement'
    | '/_authenticated/builder/projectbudget'
    | '/_authenticated/builder/task-board'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/admin/'
    | '/_authenticated/builder/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/admin/projects/$projectId'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/builder/project/$projectId'
    | '/_authenticated/builder/project/$projectId/material-requests'
    | '/_authenticated/builder/project/$projectId/materials'
    | '/_authenticated/builder/project/$projectId/signatures'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authAuthCallbackRoute: typeof authAuthCallbackRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authPendingApprovalRoute: typeof authPendingApprovalRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier': {
      id: '/_authenticated/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof AuthenticatedSupplierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sqb-team': {
      id: '/_authenticated/sqb-team'
      path: '/sqb-team'
      fullPath: '/sqb-team'
      preLoaderRoute: typeof AuthenticatedSqbTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contractor': {
      id: '/_authenticated/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof AuthenticatedContractorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/pending-approval': {
      id: '/(auth)/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof authPendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth-callback': {
      id: '/(auth)/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof authAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder/': {
      id: '/_authenticated/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof AuthenticatedBuilderIndexRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder/task-board': {
      id: '/_authenticated/builder/task-board'
      path: '/task-board'
      fullPath: '/builder/task-board'
      preLoaderRoute: typeof AuthenticatedBuilderTaskBoardRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/projectbudget': {
      id: '/_authenticated/builder/projectbudget'
      path: '/projectbudget'
      fullPath: '/builder/projectbudget'
      preLoaderRoute: typeof AuthenticatedBuilderProjectbudgetRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/procurement': {
      id: '/_authenticated/builder/procurement'
      path: '/procurement'
      fullPath: '/builder/procurement'
      preLoaderRoute: typeof AuthenticatedBuilderProcurementRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/group-buy': {
      id: '/_authenticated/builder/group-buy'
      path: '/group-buy'
      fullPath: '/builder/group-buy'
      preLoaderRoute: typeof AuthenticatedBuilderGroupBuyRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/floor-plans': {
      id: '/_authenticated/builder/floor-plans'
      path: '/floor-plans'
      fullPath: '/builder/floor-plans'
      preLoaderRoute: typeof AuthenticatedBuilderFloorPlansRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/design-drafting': {
      id: '/_authenticated/builder/design-drafting'
      path: '/design-drafting'
      fullPath: '/builder/design-drafting'
      preLoaderRoute: typeof AuthenticatedBuilderDesignDraftingRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/contract-analyser': {
      id: '/_authenticated/builder/contract-analyser'
      path: '/contract-analyser'
      fullPath: '/builder/contract-analyser'
      preLoaderRoute: typeof AuthenticatedBuilderContractAnalyserRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/building': {
      id: '/_authenticated/builder/building'
      path: '/building'
      fullPath: '/builder/building'
      preLoaderRoute: typeof AuthenticatedBuilderBuildingRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/budget-engineer': {
      id: '/_authenticated/builder/budget-engineer'
      path: '/budget-engineer'
      fullPath: '/builder/budget-engineer'
      preLoaderRoute: typeof AuthenticatedBuilderBudgetEngineerRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/builder/architectural-studio': {
      id: '/_authenticated/builder/architectural-studio'
      path: '/architectural-studio'
      fullPath: '/builder/architectural-studio'
      preLoaderRoute: typeof AuthenticatedBuilderArchitecturalStudioRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/procurement': {
      id: '/_authenticated/admin/procurement'
      path: '/procurement'
      fullPath: '/admin/procurement'
      preLoaderRoute: typeof AuthenticatedAdminProcurementRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/floor-plans': {
      id: '/_authenticated/admin/floor-plans'
      path: '/floor-plans'
      fullPath: '/admin/floor-plans'
      preLoaderRoute: typeof AuthenticatedAdminFloorPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard-analytics': {
      id: '/_authenticated/admin/dashboard-analytics'
      path: '/dashboard-analytics'
      fullPath: '/admin/dashboard-analytics'
      preLoaderRoute: typeof AuthenticatedAdminDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity-log': {
      id: '/_authenticated/admin/activity-log'
      path: '/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/builder/project/$projectId': {
      id: '/_authenticated/builder/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/builder/project/$projectId'
      preLoaderRoute: typeof AuthenticatedBuilderProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/projects/$projectId': {
      id: '/_authenticated/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedAdminProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedAdminProjectsRoute
    }
    '/_authenticated/builder/project/$projectId/signatures': {
      id: '/_authenticated/builder/project/$projectId/signatures'
      path: '/signatures'
      fullPath: '/builder/project/$projectId/signatures'
      preLoaderRoute: typeof AuthenticatedBuilderProjectProjectIdSignaturesRouteImport
      parentRoute: typeof AuthenticatedBuilderProjectProjectIdRoute
    }
    '/_authenticated/builder/project/$projectId/materials': {
      id: '/_authenticated/builder/project/$projectId/materials'
      path: '/materials'
      fullPath: '/builder/project/$projectId/materials'
      preLoaderRoute: typeof AuthenticatedBuilderProjectProjectIdMaterialsRouteImport
      parentRoute: typeof AuthenticatedBuilderProjectProjectIdRoute
    }
    '/_authenticated/builder/project/$projectId/material-requests': {
      id: '/_authenticated/builder/project/$projectId/material-requests'
      path: '/material-requests'
      fullPath: '/builder/project/$projectId/material-requests'
      preLoaderRoute: typeof AuthenticatedBuilderProjectProjectIdMaterialRequestsRouteImport
      parentRoute: typeof AuthenticatedBuilderProjectProjectIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedAdminProjectsRouteChildren {
  AuthenticatedAdminProjectsProjectIdRoute: typeof AuthenticatedAdminProjectsProjectIdRoute
}

const AuthenticatedAdminProjectsRouteChildren: AuthenticatedAdminProjectsRouteChildren =
  {
    AuthenticatedAdminProjectsProjectIdRoute:
      AuthenticatedAdminProjectsProjectIdRoute,
  }

const AuthenticatedAdminProjectsRouteWithChildren =
  AuthenticatedAdminProjectsRoute._addFileChildren(
    AuthenticatedAdminProjectsRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityLogRoute: typeof AuthenticatedAdminActivityLogRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminDashboardAnalyticsRoute: typeof AuthenticatedAdminDashboardAnalyticsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminFloorPlansRoute: typeof AuthenticatedAdminFloorPlansRoute
  AuthenticatedAdminProcurementRoute: typeof AuthenticatedAdminProcurementRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityLogRoute: AuthenticatedAdminActivityLogRoute,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminDashboardAnalyticsRoute:
    AuthenticatedAdminDashboardAnalyticsRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminFloorPlansRoute: AuthenticatedAdminFloorPlansRoute,
  AuthenticatedAdminProcurementRoute: AuthenticatedAdminProcurementRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBuilderProjectProjectIdRouteChildren {
  AuthenticatedBuilderProjectProjectIdMaterialRequestsRoute: typeof AuthenticatedBuilderProjectProjectIdMaterialRequestsRoute
  AuthenticatedBuilderProjectProjectIdMaterialsRoute: typeof AuthenticatedBuilderProjectProjectIdMaterialsRoute
  AuthenticatedBuilderProjectProjectIdSignaturesRoute: typeof AuthenticatedBuilderProjectProjectIdSignaturesRoute
}

const AuthenticatedBuilderProjectProjectIdRouteChildren: AuthenticatedBuilderProjectProjectIdRouteChildren =
  {
    AuthenticatedBuilderProjectProjectIdMaterialRequestsRoute:
      AuthenticatedBuilderProjectProjectIdMaterialRequestsRoute,
    AuthenticatedBuilderProjectProjectIdMaterialsRoute:
      AuthenticatedBuilderProjectProjectIdMaterialsRoute,
    AuthenticatedBuilderProjectProjectIdSignaturesRoute:
      AuthenticatedBuilderProjectProjectIdSignaturesRoute,
  }

const AuthenticatedBuilderProjectProjectIdRouteWithChildren =
  AuthenticatedBuilderProjectProjectIdRoute._addFileChildren(
    AuthenticatedBuilderProjectProjectIdRouteChildren,
  )

interface AuthenticatedBuilderRouteChildren {
  AuthenticatedBuilderArchitecturalStudioRoute: typeof AuthenticatedBuilderArchitecturalStudioRoute
  AuthenticatedBuilderBudgetEngineerRoute: typeof AuthenticatedBuilderBudgetEngineerRoute
  AuthenticatedBuilderBuildingRoute: typeof AuthenticatedBuilderBuildingRoute
  AuthenticatedBuilderContractAnalyserRoute: typeof AuthenticatedBuilderContractAnalyserRoute
  AuthenticatedBuilderDesignDraftingRoute: typeof AuthenticatedBuilderDesignDraftingRoute
  AuthenticatedBuilderFloorPlansRoute: typeof AuthenticatedBuilderFloorPlansRoute
  AuthenticatedBuilderGroupBuyRoute: typeof AuthenticatedBuilderGroupBuyRoute
  AuthenticatedBuilderProcurementRoute: typeof AuthenticatedBuilderProcurementRoute
  AuthenticatedBuilderProjectbudgetRoute: typeof AuthenticatedBuilderProjectbudgetRoute
  AuthenticatedBuilderTaskBoardRoute: typeof AuthenticatedBuilderTaskBoardRoute
  AuthenticatedBuilderIndexRoute: typeof AuthenticatedBuilderIndexRoute
  AuthenticatedBuilderProjectProjectIdRoute: typeof AuthenticatedBuilderProjectProjectIdRouteWithChildren
}

const AuthenticatedBuilderRouteChildren: AuthenticatedBuilderRouteChildren = {
  AuthenticatedBuilderArchitecturalStudioRoute:
    AuthenticatedBuilderArchitecturalStudioRoute,
  AuthenticatedBuilderBudgetEngineerRoute:
    AuthenticatedBuilderBudgetEngineerRoute,
  AuthenticatedBuilderBuildingRoute: AuthenticatedBuilderBuildingRoute,
  AuthenticatedBuilderContractAnalyserRoute:
    AuthenticatedBuilderContractAnalyserRoute,
  AuthenticatedBuilderDesignDraftingRoute:
    AuthenticatedBuilderDesignDraftingRoute,
  AuthenticatedBuilderFloorPlansRoute: AuthenticatedBuilderFloorPlansRoute,
  AuthenticatedBuilderGroupBuyRoute: AuthenticatedBuilderGroupBuyRoute,
  AuthenticatedBuilderProcurementRoute: AuthenticatedBuilderProcurementRoute,
  AuthenticatedBuilderProjectbudgetRoute:
    AuthenticatedBuilderProjectbudgetRoute,
  AuthenticatedBuilderTaskBoardRoute: AuthenticatedBuilderTaskBoardRoute,
  AuthenticatedBuilderIndexRoute: AuthenticatedBuilderIndexRoute,
  AuthenticatedBuilderProjectProjectIdRoute:
    AuthenticatedBuilderProjectProjectIdRouteWithChildren,
}

const AuthenticatedBuilderRouteWithChildren =
  AuthenticatedBuilderRoute._addFileChildren(AuthenticatedBuilderRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRouteWithChildren
  AuthenticatedContractorRoute: typeof AuthenticatedContractorRoute
  AuthenticatedSqbTeamRoute: typeof AuthenticatedSqbTeamRoute
  AuthenticatedSupplierRoute: typeof AuthenticatedSupplierRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBuilderRoute: AuthenticatedBuilderRouteWithChildren,
  AuthenticatedContractorRoute: AuthenticatedContractorRoute,
  AuthenticatedSqbTeamRoute: AuthenticatedSqbTeamRoute,
  AuthenticatedSupplierRoute: AuthenticatedSupplierRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authAuthCallbackRoute: authAuthCallbackRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authPendingApprovalRoute: authPendingApprovalRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
